### ISSUE TITLE
some tiny problems exists in this project

### ISSUE THREAD

**Issue by yizhilsy** [lorenzobasile/IDCorrelation#1]
https://github.com/lorenzobasile/IDCorrelation/blob/83bc0990108542353b731828e6fdbe5c2d00015c/extract_representations.py#L30C1-L51C52
hi! In the batchsize loop code above, N will be 2 in the case of using param dataset as imagenet because x is a structure of image list and label list instead of the right batchsize(such as 256), which can result in calculating wrong representations with wrong rows influencing the following idcor calculates.

 https://github.com/lorenzobasile/IDCorrelation/blob/83bc0990108542353b731828e6fdbe5c2d00015c/mnist.py#L59C1-L64C42
And in this python file, it lacks the code to pre-create the results/mnist folder, which also will makes faulty.

please check it, thanks!

**Comment by lorenzobasile** [comment]
Hi! Thank you for spotting these bugs, we have modified the two files to solve these issues. Please let us know if problems persist.

**Comment by yizhilsy** [comment]
> Hi! Thank you for spotting these bugs, we have modified the two files to solve these issues. Please let us know if problems persist.

Hi! Thank you for solving these problems! I have tested and ascertained that all bugs had been fixed. Thank you for your contributions and works!
